/*
 * SwaggerPetstoreOpenAPI30Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package io.swagger.petstore.authentication;

/**
 * A data class for Custom Header Signature credentials.
 */
public class ApiKeyModel {
    private String apiKey;

    /**
     * A Constructor for ApiKeyModel.
     */
    private ApiKeyModel(String apiKey) {
        this.apiKey = apiKey;
    }

    /**
     * Getter for apiKey.
     * @return apiKey The value of api_key.
     */
    public String getApiKey() {
        return this.apiKey;
    }

    /**
     * Builds a new {@link ApiKeyModel.Builder} object.
     * Creates the instance with the state of the current auth model.
     * @return a new {@link ApiKeyModel.Builder} object.
     */
    public Builder toBuilder() {
        return new Builder(getApiKey());
    }

    /**
     * A Builder class for Custom Header Signature credentials.
     */
    public static class Builder {
        private String apiKey;

        /**
         * The constructor with required auth credentials.
         * @param apiKey The value of ApiKey.
         */
        public Builder(String apiKey) {
            if (apiKey == null) {
                throw new NullPointerException("ApiKey cannot be null.");
            }

            this.apiKey = apiKey;
        }

        /**
         * Setter for apiKey.
         * @param apiKey The value of api_key.
         * @return Builder The current instance of Builder.
         */
        public Builder apiKey(String apiKey) {
            if (apiKey == null) {
                throw new NullPointerException("ApiKey cannot be null.");
            }

            this.apiKey = apiKey;
            return this;
        }

        /**
         * Builds the instance of ApiKeyModel using the provided credentials.
         * @return The instance of ApiKeyModel.
         */
        public ApiKeyModel build() {
            return new ApiKeyModel(apiKey);
        }
    }
}