/*
 * SwaggerPetstoreOpenAPI30Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package io.swagger.petstore.authentication;

import io.swagger.petstore.models.OAuthScopePetstoreAuthEnum;
import io.swagger.petstore.models.OAuthToken;
import java.util.List;

/**
 * A data class for OAuth 2 Implicit Grant credentials.
 */
public class PetstoreAuthModel {
    private String oAuthClientId;
    private String oAuthRedirectUri;
    private OAuthToken oAuthToken;
    private List<OAuthScopePetstoreAuthEnum> oAuthScopes;

    /**
     * A Constructor for PetstoreAuthModel.
     */
    private PetstoreAuthModel(String oAuthClientId, String oAuthRedirectUri, OAuthToken oAuthToken,
            List<OAuthScopePetstoreAuthEnum> oAuthScopes) {
        this.oAuthClientId = oAuthClientId;
        this.oAuthRedirectUri = oAuthRedirectUri;
        this.oAuthToken = oAuthToken;
        this.oAuthScopes = oAuthScopes;
    }

    /**
     * Getter for oAuthClientId.
     * @return oAuthClientId The value of OAuthClientId.
     */
    public String getOAuthClientId() {
        return this.oAuthClientId;
    }

    /**
     * Getter for oAuthRedirectUri.
     * @return oAuthRedirectUri The value of OAuthRedirectUri.
     */
    public String getOAuthRedirectUri() {
        return this.oAuthRedirectUri;
    }

    /**
     * Getter for oAuthToken.
     * @return oAuthToken The value of OAuthToken.
     */
    public OAuthToken getOAuthToken() {
        return this.oAuthToken;
    }

    /**
     * Getter for oAuthScopes.
     * @return oAuthScopes The value of OAuthScopes.
     */
    public List<OAuthScopePetstoreAuthEnum> getOAuthScopes() {
        return this.oAuthScopes;
    }

    /**
     * Builds a new {@link PetstoreAuthModel.Builder} object.
     * Creates the instance with the state of the current auth model.
     * @return a new {@link PetstoreAuthModel.Builder} object.
     */
    public Builder toBuilder() {
        return new Builder(getOAuthClientId(), getOAuthRedirectUri())
            .oAuthToken(getOAuthToken())
            .oAuthScopes(getOAuthScopes());
    }

    /**
     * A Builder class for OAuth 2 Implicit Grant credentials.
     */
    public static class Builder {
        private String oAuthClientId;
        private String oAuthRedirectUri;
        private OAuthToken oAuthToken;
        private List<OAuthScopePetstoreAuthEnum> oAuthScopes;

        /**
         * The constructor with required auth credentials.
         * @param oAuthClientId The value of OAuthClientId.
         * @param oAuthRedirectUri The value of OAuthRedirectUri.
         */
        public Builder(String oAuthClientId, String oAuthRedirectUri) {
            if (oAuthClientId == null) {
                throw new NullPointerException("OAuthClientId cannot be null.");
            }

            if (oAuthRedirectUri == null) {
                throw new NullPointerException("OAuthRedirectUri cannot be null.");
            }

            this.oAuthClientId = oAuthClientId;
            this.oAuthRedirectUri = oAuthRedirectUri;
        }

        /**
         * Setter for oAuthClientId.
         * @param oAuthClientId The value of OAuthClientId.
         * @return Builder The current instance of Builder.
         */
        public Builder oAuthClientId(String oAuthClientId) {
            if (oAuthClientId == null) {
                throw new NullPointerException("OAuthClientId cannot be null.");
            }

            this.oAuthClientId = oAuthClientId;
            return this;
        }

        /**
         * Setter for oAuthRedirectUri.
         * @param oAuthRedirectUri The value of OAuthRedirectUri.
         * @return Builder The current instance of Builder.
         */
        public Builder oAuthRedirectUri(String oAuthRedirectUri) {
            if (oAuthRedirectUri == null) {
                throw new NullPointerException("OAuthRedirectUri cannot be null.");
            }

            this.oAuthRedirectUri = oAuthRedirectUri;
            return this;
        }

        /**
         * Setter for oAuthToken.
         * @param oAuthToken The value of OAuthToken.
         * @return Builder The current instance of Builder.
         */
        public Builder oAuthToken(OAuthToken oAuthToken) {
            this.oAuthToken = oAuthToken;
            return this;
        }

        /**
         * Setter for oAuthScopes.
         * @param oAuthScopes The value of OAuthScopes.
         * @return Builder The current instance of Builder.
         */
        public Builder oAuthScopes(List<OAuthScopePetstoreAuthEnum> oAuthScopes) {
            this.oAuthScopes = oAuthScopes;
            return this;
        }

        /**
         * Builds the instance of PetstoreAuthModel using the provided credentials.
         * @return The instance of PetstoreAuthModel.
         */
        public PetstoreAuthModel build() {
            return new PetstoreAuthModel(oAuthClientId, oAuthRedirectUri, oAuthToken, oAuthScopes);
        }
    }
}