/*
 * SwaggerPetstoreOpenAPI30Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package io.swagger.petstore;

import io.swagger.petstore.authentication.ApiKeyCredentials;
import io.swagger.petstore.authentication.ApiKeyModel;
import io.swagger.petstore.authentication.PetstoreAuthCredentials;
import io.swagger.petstore.authentication.PetstoreAuthModel;
import io.swagger.petstore.http.client.ReadonlyHttpClientConfiguration;

/**
 * Configuration Interface for the library.
 */
public interface Configuration {

    /**
     * Current API environment.
     * @return a copy of environment
     */
    Environment getEnvironment();

    /**
     * Http Client Configuration instance.
     * @return a copy of httpClientConfig
     */
    ReadonlyHttpClientConfiguration getHttpClientConfig();

    /**
     * The timeout to use for making HTTP requests. The timeout to use for making HTTP requests.
     * @return a copy of timeout
     */
    long timeout();

    /**
     * The credentials to use with PetstoreAuth.
     * @return petstoreAuthCredentials
     */
    PetstoreAuthCredentials getPetstoreAuthCredentials();

    /**
     * The auth credential model for PetstoreAuth.
     * @return the instance of PetstoreAuthModel
     */
    PetstoreAuthModel getPetstoreAuthModel();

    /**
     * The credentials to use with ApiKey.
     * @return apiKeyCredentials
     */
    ApiKeyCredentials getApiKeyCredentials();

    /**
     * The auth credential model for ApiKey.
     * @return the instance of ApiKeyModel
     */
    ApiKeyModel getApiKeyModel();

    /**
     * Get base URI by current environment.
     * @param server Server for which to get the base URI
     * @return Processed base URI
     */
    String getBaseUri(Server server);

    /**
     * Get base URI by current environment.
     * @return Processed base URI
     */
    String getBaseUri();
}
