/*
 * SwaggerPetstoreOpenAPI30Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package io.swagger.petstore;

import io.apimatic.core.GlobalConfiguration;
import io.apimatic.coreinterfaces.authentication.Authentication;
import io.apimatic.coreinterfaces.compatibility.CompatibilityFactory;
import io.apimatic.coreinterfaces.http.HttpClient;
import io.apimatic.okhttpclient.adapter.OkClient;
import io.swagger.petstore.authentication.ApiKeyCredentials;
import io.swagger.petstore.authentication.ApiKeyManager;
import io.swagger.petstore.authentication.ApiKeyModel;
import io.swagger.petstore.authentication.PetstoreAuthCredentials;
import io.swagger.petstore.authentication.PetstoreAuthManager;
import io.swagger.petstore.authentication.PetstoreAuthModel;
import io.swagger.petstore.controllers.PetController;
import io.swagger.petstore.controllers.StoreController;
import io.swagger.petstore.controllers.UserController;
import io.swagger.petstore.http.client.HttpCallback;
import io.swagger.petstore.http.client.HttpClientConfiguration;
import io.swagger.petstore.http.client.ReadonlyHttpClientConfiguration;
import java.util.AbstractMap.SimpleEntry;
import java.util.HashMap;
import java.util.Map;
import java.util.function.Consumer;

/**
 * Gateway class for the library.
 * This class acts as a factory for Controllers.
 * It holds the state of the SDK.
 */
public final class SwaggerPetstoreOpenAPI30Client implements Configuration {

    /**
     * Private store for controllers.
     */
    private PetController pet;
    private StoreController store;
    private UserController user;

    private static final CompatibilityFactory compatibilityFactory = new CompatibilityFactoryImpl();

    private static String userAgent = "APIMATIC 3.0";

    /**
     * Current API environment.
     */
    private final Environment environment;

    /**
     * The HTTP Client instance to use for making HTTP requests.
     */
    private final HttpClient httpClient;

    /**
     * Http Client Configuration instance.
     */
    private final ReadonlyHttpClientConfiguration httpClientConfig;

    /**
     * PetstoreAuthManager.
     */
    private PetstoreAuthManager petstoreAuthManager;

    /**
     * The instance of PetstoreAuthModel.
     */
    private PetstoreAuthModel petstoreAuthModel;

    /**
     * ApiKeyManager.
     */
    private ApiKeyManager apiKeyManager;

    /**
     * The instance of ApiKeyModel.
     */
    private ApiKeyModel apiKeyModel;

    /**
     * Map of authentication Managers.
     */
    private Map<String, Authentication> authentications;

    /**
     * Callback to be called before and after the HTTP call for an endpoint is made.
     */
    private final HttpCallback httpCallback;

    private SwaggerPetstoreOpenAPI30Client(Environment environment, HttpClient httpClient,
            ReadonlyHttpClientConfiguration httpClientConfig, PetstoreAuthModel petstoreAuthModel,
            ApiKeyModel apiKeyModel, Map<String, Authentication> authentications,
            HttpCallback httpCallback) {
        this.environment = environment;
        this.httpClient = httpClient;
        this.httpClientConfig = httpClientConfig;
        this.httpCallback = httpCallback;
        this.authentications = 
                (authentications == null) ? new HashMap<>() : new HashMap<>(authentications);
        this.petstoreAuthModel = petstoreAuthModel;
        this.apiKeyModel = apiKeyModel;

        if (this.authentications.containsKey("petstore_auth")) {
            this.petstoreAuthManager =
                    (PetstoreAuthManager) this.authentications.get("petstore_auth");
        }

        if (!this.authentications.containsKey("petstore_auth")
                || !getPetstoreAuthCredentials().equals(petstoreAuthModel.getOAuthClientId(),
                        petstoreAuthModel.getOAuthRedirectUri(), petstoreAuthModel.getOAuthToken(),
                        petstoreAuthModel.getOAuthScopes())) {
            this.petstoreAuthManager = new PetstoreAuthManager(petstoreAuthModel);
            this.authentications.put("petstore_auth", petstoreAuthManager);
        }

        if (this.authentications.containsKey("api_key")) {
            this.apiKeyManager = (ApiKeyManager) this.authentications.get("api_key");
        }

        if (!this.authentications.containsKey("api_key")
                || !getApiKeyCredentials().equals(apiKeyModel.getApiKey())) {
            this.apiKeyManager = new ApiKeyManager(apiKeyModel);
            this.authentications.put("api_key", apiKeyManager);
        }

        GlobalConfiguration globalConfig = new GlobalConfiguration.Builder()
                .httpClient(httpClient).baseUri(server -> getBaseUri(server))
                .compatibilityFactory(compatibilityFactory)
                .authentication(this.authentications)
                .callback(httpCallback)
                .userAgent(userAgent)
                .build();
        this.petstoreAuthManager.applyGlobalConfiguration(globalConfig);

        pet = new PetController(globalConfig);
        store = new StoreController(globalConfig);
        user = new UserController(globalConfig);
    }

    /**
     * Shutdown the underlying HttpClient instance.
     */
    public static void shutdown() {
        OkClient.shutdown();
    }

    /**
     * Get the instance of PetController.
     * @return pet
     */
    public PetController getPetController() {
        return pet;
    }

    /**
     * Get the instance of StoreController.
     * @return store
     */
    public StoreController getStoreController() {
        return store;
    }

    /**
     * Get the instance of UserController.
     * @return user
     */
    public UserController getUserController() {
        return user;
    }

    /**
     * Current API environment.
     * @return environment
     */
    public Environment getEnvironment() {
        return environment;
    }

    /**
     * The HTTP Client instance to use for making HTTP requests.
     * @return httpClient
     */
    private HttpClient getHttpClient() {
        return httpClient;
    }

    /**
     * Http Client Configuration instance.
     * @return httpClientConfig
     */
    public ReadonlyHttpClientConfiguration getHttpClientConfig() {
        return httpClientConfig;
    }

    /**
     * The credentials to use with PetstoreAuth.
     * @return petstoreAuthCredentials
     */
    public PetstoreAuthCredentials getPetstoreAuthCredentials() {
        return petstoreAuthManager;
    }

    /**
     * The auth credential model for PetstoreAuth.
     * @return the instance of PetstoreAuthModel
     */
    public PetstoreAuthModel getPetstoreAuthModel() {
        return petstoreAuthModel;
    }
    /**
     * The credentials to use with ApiKey.
     * @return apiKeyCredentials
     */
    public ApiKeyCredentials getApiKeyCredentials() {
        return apiKeyManager;
    }

    /**
     * The auth credential model for ApiKey.
     * @return the instance of ApiKeyModel
     */
    public ApiKeyModel getApiKeyModel() {
        return apiKeyModel;
    }
    /**
     * The timeout to use for making HTTP requests.
     * @deprecated This method will be removed in a future version. Use
     *             {@link #getHttpClientConfig()} instead.
     *
     * @return timeout
     */
    @Deprecated
    public long timeout() {
        return httpClientConfig.getTimeout();
    }

    /**
     * Get base URI by current environment.
     * @param server Server for which to get the base URI
     * @return Processed base URI
     */
    public String getBaseUri(Server server) {
        Map<String, SimpleEntry<Object, Boolean>> parameters = new HashMap<>();
        StringBuilder baseUrl = new StringBuilder(environmentMapper(environment, server));
        ApiHelper.appendUrlWithTemplateParameters(baseUrl, parameters);
        return baseUrl.toString();
    }

    /**
     * Get base URI by current environment.
     * @return Processed base URI
     */
    public String getBaseUri() {
        return getBaseUri(Server.ENUM_DEFAULT);
    }


    /**
     * Get base URI by current environment.
     * 
     * @param server string for which to get the base URI
     * @return Processed base URI
     */
    public String getBaseUri(String server) {
        return getBaseUri(Server.fromString(server));
    }


    /**
     * Base URLs by environment and server aliases.
     * @param environment Environment for which to get the base URI
     * @param server Server for which to get the base URI
     * @return base URL
     */
    private static String environmentMapper(Environment environment, Server server) {
        if (environment.equals(Environment.PRODUCTION)) {
            if (server.equals(Server.ENUM_DEFAULT)) {
                return "http://petstore.swagger.io/v1/api/v3";
            }
            if (server.equals(Server.AUTH_SERVER)) {
                return "https://petstore3.swagger.io/oauth";
            }
        }
        return "http://petstore.swagger.io/v1/api/v3";
    }

    /**
     * Converts this SwaggerPetstoreOpenAPI30Client into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "SwaggerPetstoreOpenAPI30Client [" + "environment=" + environment
                + ", httpClientConfig=" + httpClientConfig + ", authentications=" + authentications
                + "]";
    }

    /**
     * Builds a new {@link SwaggerPetstoreOpenAPI30Client.Builder} object.
     * Creates the instance with the state of the current client.
     * @return a new {@link SwaggerPetstoreOpenAPI30Client.Builder} object
     */
    public Builder newBuilder() {
        Builder builder = new Builder();
        builder.environment = getEnvironment();
        builder.httpClient = getHttpClient();
        builder.petstoreAuthCredentials(getPetstoreAuthModel()
                .toBuilder().build());
        builder.apiKeyCredentials(getApiKeyModel()
                .toBuilder().build());
        builder.authentications = authentications;
        builder.httpCallback = httpCallback;
        builder.httpClientConfig(configBldr -> configBldr =
                ((HttpClientConfiguration) httpClientConfig).newBuilder());
        return builder;
    }

    /**
     * Class to build instances of {@link SwaggerPetstoreOpenAPI30Client}.
     */
    public static class Builder {

        private Environment environment = Environment.PRODUCTION;
        private HttpClient httpClient;
        private PetstoreAuthModel petstoreAuthModel = new PetstoreAuthModel.Builder("", "").build();
        private ApiKeyModel apiKeyModel = new ApiKeyModel.Builder("").build();
        private Map<String, Authentication> authentications = null;
        private HttpCallback httpCallback = null;
        private HttpClientConfiguration.Builder httpClientConfigBuilder =
                new HttpClientConfiguration.Builder();


        /**
         * Credentials setter for PetstoreAuthCredentials.
         * @param petstoreAuthModel The instance of PetstoreAuthModel.
         * @return The current instance of builder.
         */
        public Builder petstoreAuthCredentials(PetstoreAuthModel petstoreAuthModel) {
            this.petstoreAuthModel = petstoreAuthModel;
            return this;
        }

        /**
         * Credentials setter for ApiKeyCredentials.
         * @param apiKeyModel The instance of ApiKeyModel.
         * @return The current instance of builder.
         */
        public Builder apiKeyCredentials(ApiKeyModel apiKeyModel) {
            this.apiKeyModel = apiKeyModel;
            return this;
        }

        /**
         * Current API environment.
         * @param environment The environment for client.
         * @return Builder
         */
        public Builder environment(Environment environment) {
            this.environment = environment;
            return this;
        }

        /**
         * The timeout to use for making HTTP requests.
         * @deprecated This method will be removed in a future version. Use
         *             {@link #httpClientConfig(Consumer) httpClientConfig} instead.
         * @param timeout must be greater then 0.
         * @return Builder
         */
        @Deprecated
        public Builder timeout(long timeout) {
            this.httpClientConfigBuilder.timeout(timeout);
            return this;
        }

        /**
         * HttpCallback.
         * @param httpCallback Callback to be called before and after the HTTP call.
         * @return Builder
         */
        public Builder httpCallback(HttpCallback httpCallback) {
            this.httpCallback = httpCallback;
            return this;
        }

        /**
         * Setter for the Builder of httpClientConfiguration, takes in an operation to be performed
         * on the builder instance of HTTP client configuration.
         * 
         * @param action Consumer for the builder of httpClientConfiguration.
         * @return Builder
         */
        public Builder httpClientConfig(Consumer<HttpClientConfiguration.Builder> action) {
            action.accept(httpClientConfigBuilder);
            return this;
        }

        /**
         * Builds a new SwaggerPetstoreOpenAPI30Client object using the set fields.
         * @return SwaggerPetstoreOpenAPI30Client
         */
        public SwaggerPetstoreOpenAPI30Client build() {
            HttpClientConfiguration httpClientConfig = httpClientConfigBuilder.build();
            httpClient = new OkClient(httpClientConfig.getConfiguration(), compatibilityFactory);

            return new SwaggerPetstoreOpenAPI30Client(environment, httpClient, httpClientConfig,
                    petstoreAuthModel, apiKeyModel, authentications, httpCallback);
        }
    }
}