/*
 * SwaggerPetstoreOpenAPI30Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package io.swagger.petstore.utilities;

import io.apimatic.core.utilities.XmlLocalDateTimeHelper;

public class XmlDateTimeHelper extends XmlLocalDateTimeHelper {
    
}