/*
 * SwaggerPetstoreOpenAPI30Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package io.swagger.petstore.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.List;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementWrapper;

/**
 * This is a model class for Pet type.
 */
public class Pet {
    private Long id;
    private String name;
    private Category category;
    private List<String> photoUrls;
    private List<Tag> tags;
    private Status1Enum status;

    /**
     * Default constructor.
     */
    public Pet() {
    }

    /**
     * Initialization constructor.
     * @param  name  String value for name.
     * @param  photoUrls  List of String value for photoUrls.
     * @param  id  Long value for id.
     * @param  category  Category value for category.
     * @param  tags  List of Tag value for tags.
     * @param  status  Status1Enum value for status.
     */
    public Pet(
            String name,
            List<String> photoUrls,
            Long id,
            Category category,
            List<Tag> tags,
            Status1Enum status) {
        this.id = id;
        this.name = name;
        this.category = category;
        this.photoUrls = photoUrls;
        this.tags = tags;
        this.status = status;
    }

    /**
     * Getter for Id.
     * @return Returns the Long
     */
    @JsonGetter("id")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "id")
    public Long getId() {
        return id;
    }

    /**
     * Setter for Id.
     * @param id Value for Long
     */
    @JsonSetter("id")
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for Name.
     * @return Returns the String
     */
    @JsonGetter("name")
    @XmlElement(name = "name")
    public String getName() {
        return name;
    }

    /**
     * Setter for Name.
     * @param name Value for String
     */
    @JsonSetter("name")
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for Category.
     * @return Returns the Category
     */
    @JsonGetter("category")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "category")
    public Category getCategory() {
        return category;
    }

    /**
     * Setter for Category.
     * @param category Value for Category
     */
    @JsonSetter("category")
    public void setCategory(Category category) {
        this.category = category;
    }

    /**
     * Getter for PhotoUrls.
     * @return Returns the List of String
     */
    @JsonGetter("photoUrls")
    @XmlElementWrapper(name = "photoUrls")
    @XmlElement(name = "photoUrl")
    public List<String> getPhotoUrls() {
        return photoUrls;
    }

    /**
     * Setter for PhotoUrls.
     * @param photoUrls Value for List of String
     */
    @JsonSetter("photoUrls")
    public void setPhotoUrls(List<String> photoUrls) {
        this.photoUrls = photoUrls;
    }

    /**
     * Getter for Tags.
     * @return Returns the List of Tag
     */
    @JsonGetter("tags")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElementWrapper(name = "tags")
    @XmlElement(name = "tag")
    public List<Tag> getTags() {
        return tags;
    }

    /**
     * Setter for Tags.
     * @param tags Value for List of Tag
     */
    @JsonSetter("tags")
    public void setTags(List<Tag> tags) {
        this.tags = tags;
    }

    /**
     * Getter for Status.
     * pet status in the store
     * @return Returns the Status1Enum
     */
    @JsonGetter("status")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "status")
    public Status1Enum getStatus() {
        return status;
    }

    /**
     * Setter for Status.
     * pet status in the store
     * @param status Value for Status1Enum
     */
    @JsonSetter("status")
    public void setStatus(Status1Enum status) {
        this.status = status;
    }

    /**
     * Converts this Pet into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Pet [" + "name=" + name + ", photoUrls=" + photoUrls + ", id=" + id + ", category="
                + category + ", tags=" + tags + ", status=" + status + "]";
    }

    /**
     * Builds a new {@link Pet.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Pet.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(name, photoUrls)
                .id(getId())
                .category(getCategory())
                .tags(getTags())
                .status(getStatus());
        return builder;
    }

    /**
     * Class to build instances of {@link Pet}.
     */
    public static class Builder {
        private String name;
        private List<String> photoUrls;
        private Long id;
        private Category category;
        private List<Tag> tags;
        private Status1Enum status;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  name  String value for name.
         * @param  photoUrls  List of String value for photoUrls.
         */
        public Builder(String name, List<String> photoUrls) {
            this.name = name;
            this.photoUrls = photoUrls;
        }

        /**
         * Setter for name.
         * @param  name  String value for name.
         * @return Builder
         */
        public Builder name(String name) {
            this.name = name;
            return this;
        }

        /**
         * Setter for photoUrls.
         * @param  photoUrls  List of String value for photoUrls.
         * @return Builder
         */
        public Builder photoUrls(List<String> photoUrls) {
            this.photoUrls = photoUrls;
            return this;
        }

        /**
         * Setter for id.
         * @param  id  Long value for id.
         * @return Builder
         */
        public Builder id(Long id) {
            this.id = id;
            return this;
        }

        /**
         * Setter for category.
         * @param  category  Category value for category.
         * @return Builder
         */
        public Builder category(Category category) {
            this.category = category;
            return this;
        }

        /**
         * Setter for tags.
         * @param  tags  List of Tag value for tags.
         * @return Builder
         */
        public Builder tags(List<Tag> tags) {
            this.tags = tags;
            return this;
        }

        /**
         * Setter for status.
         * @param  status  Status1Enum value for status.
         * @return Builder
         */
        public Builder status(Status1Enum status) {
            this.status = status;
            return this;
        }

        /**
         * Builds a new {@link Pet} object using the set fields.
         * @return {@link Pet}
         */
        public Pet build() {
            return new Pet(name, photoUrls, id, category, tags, status);
        }
    }
}
